### ISSUE TITLE
编译出现问题

### ISSUE THREAD

**Issue by ZHAOFEGNSHUN** [LiZhengXiao99/Navigation-Learning#1]
In file included from /home/zfs/gici-open/include/gici/estimate/graph.h:55,                                                              from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/include/gici/stream/streaming.h:18,                                                            from /home/zfs/gici-open/include/gici/stream/data_integration.h:11,                                                     from /home/zfs/gici-open/src/stream/data_integration.cpp:9:                                            /home/zfs/gici-open/include/gici/estimate/homogeneous_point_local_parameterization.h:57:40: error: expected class-name before ‘,’ token                                                                                                          57 |     public ceres::LocalParameterization,                                                                              |                                        ^                                                                        In file included from /home/zfs/gici-open/include/gici/estimate/graph.h:56,                                                              from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/include/gici/stream/streaming.h:18,                                                            from /home/zfs/gici-open/include/gici/stream/data_integration.h:11,                                                     from /home/zfs/gici-open/src/stream/data_integration.cpp:9:                                            /home/zfs/gici-open/include/gici/estimate/parameter_block.h:143:20: error: ‘LocalParameterization’ in namespace ‘ceres’ does not name a type                                                                                                  143 |       const ceres::LocalParameterization* localParameterizationPtr)                                                   |                    ^~~~~~~~~~~~~~~~~~~~~                                                                        /home/zfs/gici-open/include/gici/estimate/parameter_block.h:150:24: error: ‘LocalParameterization’ in namespace ‘ceres’ does not name a type                                                                                                  150 |   virtual const ceres::LocalParameterization* localParameterizationPtr() const                                        |                        ^~~~~~~~~~~~~~~~~~~~~                                                                    /home/zfs/gici-open/include/gici/estimate/parameter_block.h:164:16: error: ‘LocalParameterization’ in namespace ‘ceres’ does not name a type                                                                                                  164 |   const ceres::LocalParameterization* local_parameterization_ptr_;                                                    |                ^~~~~~~~~~~~~~~~~~~~~                                                                            /home/zfs/gici-open/include/gici/estimate/parameter_block.h: In constructor ‘gici::ParameterBlock::ParameterBlock()’: /home/zfs/gici-open/include/gici/estimate/parameter_block.h:64:9: error: class ‘gici::ParameterBlock’ does not have any field named ‘local_parameterization_ptr_’                                                                              64 |       , local_parameterization_ptr_(nullptr)                                                                          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                             /home/zfs/gici-open/include/gici/estimate/parameter_block.h: In member function ‘virtual void gici::ParameterBlock::setLocalParameterizationPtr(const int*)’:                                                                                 /home/zfs/gici-open/include/gici/estimate/parameter_block.h:145:5: error: ‘local_parameterization_ptr_’ was not declared in this scope; did you mean ‘localParameterizationPtr’?                                                              145 |     local_parameterization_ptr_ = localParameterizationPtr;                                                           |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                       |     localParameterizationPtr                                                                                    In file included from /home/zfs/gici-open/include/gici/estimate/graph.h:57,                                                              from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/include/gici/stream/streaming.h:18,                                                            from /home/zfs/gici-open/include/gici/stream/data_integration.h:11,                                                     from /home/zfs/gici-open/src/stream/data_integration.cpp:9:                                            /home/zfs/gici-open/include/gici/estimate/pose_local_parameterization.h: At global scope:                               /home/zfs/gici-open/include/gici/estimate/pose_local_parameterization.h:62:40: error: expected class-name before ‘,’ token                                                                                                                       62 |     public ceres::LocalParameterization,                                                                              |                                        ^                                                                        In file included from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/include/gici/stream/streaming.h:18,                                                            from /home/zfs/gici-open/include/gici/stream/data_integration.h:11,                                                     from /home/zfs/gici-open/src/stream/data_integration.cpp:9:                                            /home/zfs/gici-open/include/gici/estimate/graph.h:309:7: error: ‘ceres::LocalParameterization’ has not been declared    309 |       ceres::LocalParameterization* local_parameterization);                                                          |       ^~~~~                                                                                                     /home/zfs/gici-open/include/gici/estimate/graph.h:319:7: error: ‘ceres::LocalParameterization’ has not been declared    319 |       ceres::LocalParameterization* local_parameterization)                                                           |       ^~~~~                                                                                                     In file included from /home/zfs/gici-open/include/gici/estimate/graph.h:55,                                                              from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/src/utility/option.cpp:14:                                                    /home/zfs/gici-open/include/gici/estimate/homogeneous_point_local_parameterization.h:57:40: error: expected class-name before ‘,’ token                                                                                                          57 |     public ceres::LocalParameterization,                                                                              |                                        ^                                                                        In file included from /home/zfs/gici-open/include/gici/estimate/graph.h:56,                                                              from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/src/utility/option.cpp:14:                                                    /home/zfs/gici-open/include/gici/estimate/parameter_block.h:143:20: error: ‘LocalParameterization’ in namespace ‘ceres’ does not name a type                                                                                                  143 |       const ceres::LocalParameterization* localParameterizationPtr)                                                   |                    ^~~~~~~~~~~~~~~~~~~~~                                                                        /home/zfs/gici-open/include/gici/estimate/parameter_block.h:150:24: error: ‘LocalParameterization’ in namespace ‘ceres’ does not name a type                                                                                                  150 |   virtual const ceres::LocalParameterization* localParameterizationPtr() const                                        |                        ^~~~~~~~~~~~~~~~~~~~~                                                                    /home/zfs/gici-open/include/gici/estimate/parameter_block.h:164:16: error: ‘LocalParameterization’ in namespace ‘ceres’ does not name a type                                                                                                  164 |   const ceres::LocalParameterization* local_parameterization_ptr_;                                                    |                ^~~~~~~~~~~~~~~~~~~~~                                                                            /home/zfs/gici-open/include/gici/estimate/parameter_block.h: In constructor ‘gici::ParameterBlock::ParameterBlock()’: /home/zfs/gici-open/include/gici/estimate/parameter_block.h:64:9: error: class ‘gici::ParameterBlock’ does not have any field named ‘local_parameterization_ptr_’                                                                              64 |       , local_parameterization_ptr_(nullptr)                                                                          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                             /home/zfs/gici-open/include/gici/estimate/parameter_block.h: In member function ‘virtual void gici::ParameterBlock::setLocalParameterizationPtr(const int*)’:                                                                                 /home/zfs/gici-open/include/gici/estimate/parameter_block.h:145:5: error: ‘local_parameterization_ptr_’ was not declared in this scope; did you mean ‘localParameterizationPtr’?                                                              145 |     local_parameterization_ptr_ = localParameterizationPtr;                                                           |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                       |     localParameterizationPtr                                                                                    In file included from /home/zfs/gici-open/include/gici/estimate/graph.h:57,                                                              from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/src/utility/option.cpp:14:                                                    /home/zfs/gici-open/include/gici/estimate/pose_local_parameterization.h: At global scope:                               /home/zfs/gici-open/include/gici/estimate/pose_local_parameterization.h:62:40: error: expected class-name before ‘,’ token                                                                                                                       62 |     public ceres::LocalParameterization,                                                                              |                                        ^                                                                        In file included from /home/zfs/gici-open/include/gici/estimate/estimator_types.h:30,                                                    from /home/zfs/gici-open/include/gici/stream/formator.h:19,                                                             from /home/zfs/gici-open/src/utility/option.cpp:14:                                                    /home/zfs/gici-open/include/gici/estimate/graph.h:309:7: error: ‘ceres::LocalParameterization’ has not been declared    309 |       ceres::LocalParameterization* local_parameterization);                                                          |       ^~~~~                                                                                                     /home/zfs/gici-open/include/gici/estimate/graph.h:319:7: error: ‘ceres::LocalParameterization’ has not been declared    319 |       ceres::LocalParameterization* local_parameterization)                                                           |       ^~~~~                                                                                                     In file included from /home/zfs/gici-open/include/gici/estimate/estimator_base.h:16,                                                     from /home/zfs/gici-open/include/gici/estimate/estimating.h:21,                                                         from /home/zfs/gici-open/include/gici/stream/data_integration.h:12,                                                     from /home/zfs/gici-open/src/stream/data_integration.cpp:9:                                            /home/zfs/gici-open/include/gici/estimate/marginalization_error.h: In constructor ‘gici::MarginalizationError::ParameterBlockInfo::ParameterBlockInfo(uint64_t, std::shared_ptr<gici::ParameterBlock>, size_t, bool)’:                        /home/zfs/gici-open/include/gici/estimate/marginalization_error.h:373:32: error: ‘using element_type = class gici::ParameterBlock’ {aka ‘class gici::ParameterBlock’} has no member named ‘localParameterizationPtr’; did you mean ‘setLocalParameterizationPtr’?                                                                                                 373 |       if (parameter_block_ptr->localParameterizationPtr())                                                            |                                ^~~~~~~~~~~~~~~~~~~~~~~~                                                               |                                setLocalParameterizationPtr                                                      /home/zfs/gici-open/include/gici/estimate/marginalization_error.h:375:48: error: ‘using element_type = class gici::ParameterBlock’ {aka ‘class gici::ParameterBlock’} has no member named ‘localParameterizationPtr’; did you mean ‘setLocalParameterizationPtr’?                                                                                                 375 |         local_dimension = parameter_block_ptr->localParameterizationPtr()                                             |                                                ^~~~~~~~~~~~~~~~~~~~~~~~                                               |                                                setLocalParameterizationPtr                                      In file included from /home/zfs/gici-open/include/gici/estimate/estimator_base.h:16,                                                     from /home/zfs/gici-open/include/gici/gnss/gnss_estimator_base.h:11,                                                    from /home/zfs/gici-open/include/gici/gnss/spp_estimator.h:11,                                                          from /home/zfs/gici-open/src/utility/option.cpp:19:                                                    /home/zfs/gici-open/include/gici/estimate/marginalization_error.h: In constructor ‘gici::MarginalizationError::ParameterBlockInfo::ParameterBlockInfo(uint64_t, std::shared_ptr<gici::ParameterBlock>, size_t, bool)’:                        /home/zfs/gici-open/include/gici/estimate/marginalization_error.h:373:32: error: ‘using element_type = class gici::ParameterBlock’ {aka ‘class gici::ParameterBlock’} has no member named ‘localParameterizationPtr’; did you mean ‘setLocalParameterizationPtr’?                                                                                                 373 |       if (parameter_block_ptr->localParameterizationPtr())                                                            |                                ^~~~~~~~~~~~~~~~~~~~~~~~                                                               |                                setLocalParameterizationPtr                                                      /home/zfs/gici-open/include/gici/estimate/marginalization_error.h:375:48: error: ‘using element_type = class gici::ParameterBlock’ {aka ‘class gici::ParameterBlock’} has no member named ‘localParameterizationPtr’; did you mean ‘setLocalParameterizationPtr’?                                                                                                 375 |         local_dimension = parameter_block_ptr->localParameterizationPtr()                                             |                                                ^~~~~~~~~~~~~~~~~~~~~~~~                                               |                                                setLocalParameterizationPtr                                      make[2]: *** [CMakeFiles/gici.dir/build.make:154: CMakeFiles/gici.dir/src/stream/data_integration.cpp.o] Error 1        make[2]: *** Waiting for unfinished jobs....                                                                            make[2]: *** [CMakeFiles/gici.dir/build.make:102: CMakeFiles/gici.dir/src/utility/option.cpp.o] Error 1                 make[1]: *** [CMakeFiles/Makefile2:195: CMakeFiles/gici.dir/all] Error 2                                                make: *** [Makefile:84: all] Error 2         
想请问我编译gici时，出现源文件错误是怎么回事呀？

**Comment by LiZhengXiao99** [comment]
可以参考Issue：https://github.com/chichengcn/gici-open/issues/4
