### ISSUE TITLE
导航定位算法公式理解可以尽快更新嘛

### ISSUE THREAD

**Issue by Victoira** [LiZhengXiao99/Navigation-Learning#7]
学习笔记非常棒，我最近在学习卫星姿态控制和定轨相关的算法，看到你的笔记，帮助很大，不过在看《导航定位算法公式理解》时md文件中很多公式看不到，期待作者尽快更新。

**Comment by LiZhengXiao99** [comment]
感谢支持，不过最近半年要准备考研，暂时没法更新了👻
